name: maps_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg_icons: ^0.0.1+4
  fluttertoast: ^8.2.8
  get_it: ^8.0.2
  google_fonts: ^6.2.0
  google_maps_flutter: ^2.6.1
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/svg/maps.svg
    - assets/svg/notebook.svg
    - assets/svg/intro.svg
    - assets/intro.gif
